"""
Module qui contient les constantes du projet
"""

NOMBRE_MAXIMAL_ESCRIMEUR_POULE = 7
NOMBRE_MINIMAL_ESCRIMEUR_POULE = 3

# BD

locale = ''

# PDF

COULEUR_TEXTE = '#FFFFFF'
DECALAGE_GAUCHE = 60

# Noms

LARGEUR_NOM_BASE = 60
HAUTEUR_RECTANGLE_NOM = 30
POSITIONNEMENT_HAUTEUR_RECTANGLE_NOM = 670
POSITIONNEMENT_LARGEUR_RECTANGLE_NOM = 100

# Clubs

LARGEUR_CLUB_BASE = 60
HAUTEUR_RECTANGLE_CLUB = 30
POSITIONNEMENT_HAUTEUR_RECTANGLE_CLUB = 670
POSITIONNEMENT_LARGEUR_RECTANGLE_CLUB = 160
