-- Supprimer les contraintes de clé étrangère en premier
-- Supprimer les tables d'association
DROP TABLE IF EXISTS ETRE_DANS;
DROP TABLE IF EXISTS INSCRIRE;
DROP TABLE IF EXISTS ARBITRER;
DROP TABLE IF EXISTS TOUCHE;
DROP TABLE IF EXISTS MATCHS;

-- Supprimer les tables principales
DROP TABLE IF EXISTS COMPETITION;
DROP TABLE IF EXISTS ESCRIMEUR;
DROP TABLE IF EXISTS POULE;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS CLUB;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS ARMES;